version: '3'

volumes:
  db-data:

services:
  test-db:
    container_name: test-db
    image: bitnami/postgresql
    volumes:
      - db-data:/bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=test_user
      - POSTGRESQL_PASSWORD=test_password
      - POSTGRESQL_DATABASE=postgres
